{% set version = "1.5.3" %}

package:
  name: logbook
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/L/Logbook/Logbook-{{ version }}.tar.gz
  sha256: 66f454ada0f56eae43066f604a222b09893f98c1adc18df169710761b8f32fe8 

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - logbook
  source_files:
    - tests
  requires: 
    - pip
    - pytest
    # brotlicffi isn't available on osx-arm64
    - brotlicffi  # [not (osx and arm64)]
    - brotlipy    # [osx and arm64]
  commands: 
    - pip check
    # # see https://github.com/getlogbook/logbook/issues/308
    - pytest tests -vv  # [not (osx and arm64)]
    - pytest tests -vv -k "not(test_compression_file_handler[ContextEnteringStrategy-False] or test_compression_file_handler[PushingStrategy-False])" # [not (osx and arm64)]

about:
  home: https://github.com/getlogbook/logbook
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Logbook is a nice logging replacement
  description: |
    Logbook is a nice logging replacement.
  doc_url: https://logbook.readthedocs.io
  dev_url: https://github.com/getlogbook/logbook

extra:
  recipe-maintainers:
    - maresb
    - simonvh
    - Ryan-Dmello
