{% set version = "1.5.3" %}

package:
  name: logbook
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/L/Logbook/Logbook-{{ version }}.tar.gz
  sha256: 66f454ada0f56eae43066f604a222b09893f98c1adc18df169710761b8f32fe8 

build:
 number: 7
 script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - logbook

about:
  home: https://github.com/getlogbook/logbook
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Logbook is a nice logging replacement' 

  description: |
    Logbook is a nice logging replacement.
  doc_url: http://logbook.readthedocs.org
  dev_url: https://github.com/getlogbook/logbook

extra:
  recipe-maintainers:
    - maresb
    - simonvh
    - Ryan-Dmello
