{% set version = "1.8.2" %}

package:
  name: logbook
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/L/Logbook/logbook-1.8.2.tar.gz
  sha256: 6d19797c1646ef2f518fe207ae88d2415487085044f5fa5f1cd725b9ab0dd329

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - cython
  run:
    - python
  run_constrained:
    - execnet >=1.0.9
    - sqlalchemy >=1.4

test:
  imports:
    - logbook
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - brotlipy
  commands:
    - pip check
    # # see https://github.com/getlogbook/logbook/issues/308
    - pytest tests -vv -k "not(test_compression_file_handler[ContextEnteringStrategy-False] or test_compression_file_handler[PushingStrategy-False])"

about:
  home: https://github.com/getlogbook/logbook
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Logbook is a nice logging replacement
  description: |
    Logbook is a logging system for Python that replaces the standard library's logging module. It was designed with both complex and simple applications in mind and the idea to make logging fun.
  doc_url: https://logbook.readthedocs.io
  dev_url: https://github.com/getlogbook/logbook

extra:
  recipe-maintainers:
    - maresb
    - simonvh
    - Ryan-Dmello
