travis:
  secure:
    BINSTAR_TOKEN: HrfD/WvbFTzv8ijAJrwbYIoVUgXsjoM5/K/Ikj4Rlm5c0hB8JxJoLpt/gg7/xNej20NxvrmuIQHQbodMUg6jn8QmGZwfym5M4iVvdZaXAOrlvsL3UwVwPnQiEq9hPiQRes8MEjwr0iURu1RknPDuILtRcBi2q7hhBYFWpoGVUcZmJwlicv2cwfQUmka6+Qm/1MB4p+3a2M0XTpEOMrGRKpVEAm6bc8RuhjUpbve9Np+SXodw7IymxE5Z8JAO7ypYg8zY++jmytLNhWo0SsWBykyzIdc89IwO+nv13aTjZn2UQVTsElI3SAtAzeD8tKkZVBGjn29rybdorG9sIgm5wl5Sta21j0Ohr1huTuQstxZcSQfPTxX2S6t/j7JTVjuTcTlaV88ALr3Cg2AGyRe3P/bGIx8IGzGQ0DtEZJPGPqL7jffSsKjhlNYwKN8kAOOb3AK4tHtEf14ohk8MtJIBc8RSN3Pbmh/Be3wnMEA78i0vJf6NFwBH8xOprvIs8lYBgUf4oiusSA46jkK8UQUiYkUFPOF/dLZt18wtIpkUcUlrD7YhVHKEDL8DubVrAdHo7G8nCFcbNYe1fmhm7nKc24xfvxGPtZacc/2oLGHGSvHLpwAnnLGnBw1LTZ+r5gEPVA92G963LpbaFdj3rhgiTGoiMu6MmhbC6UYqKvXS4HE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
